#!/bin/sh
#
# Copyright (c) 2012-2015, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE DISCLAIMED.  IN NO
# EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# DESCRIPTION: RNDIS + DIAG + SERIAL + ADB : ECM

echo "Switching to composition number 0x02E1"

if [ "$1" = "y" ]; then
	num="1"
else
	num="0"
fi

if [ "$#" -ge 2 ]; then
	delay=$2
else
	delay="0"
fi

if [ "$#" -ge 3 ]; then
	from_adb=$3
else
	from_adb="n"
fi

run_nomass() {
	if [ $from_adb = "n" ]
	then
		pkill adbd
	fi
	echo 0 > /sys/class/android_usb/android$num/enable
	echo 1ECB > /sys/class/android_usb/android$num/idVendor
	echo 02E1 > /sys/class/android_usb/android$num/idProduct
	echo 2 > /sys/class/android_usb/android$num/bDeviceClass
	echo 0 > /sys/class/android_usb/android$num/bDeviceSubClass
	echo 0 > /sys/class/android_usb/android$num/bDeviceProtocol
	echo AMTelecom > /sys/class/android_usb/android$num/iManufacturer
	echo 0123456789ABCDEF > /sys/class/android_usb/android$num/iSerial
	echo JMR1140 > /sys/class/android_usb/android$num/iProduct
	
	echo diag > /sys/class/android_usb/android$num/f_diag/clients
	echo smd > /sys/class/android_usb/android$num/f_serial/transports
	echo rndis,diag,serial,ffs:ecm > /sys/class/android_usb/android$num/functions
	echo 1 > /sys/class/android_usb/android$num/remote_wakeup
	echo 1 > /sys/class/android_usb/android0/f_rndis/wceis
	sleep $delay
	echo 1 > /sys/class/android_usb/android$num/enable
	if [ $from_adb = "n" ]
	then
		/etc/init.d/adbd start
	fi
}

run_mass() {
	if [ $from_adb = "n" ]
	then
		pkill adbd
	fi
	echo 0 > /sys/class/android_usb/android$num/enable
	echo 1ECB > /sys/class/android_usb/android$num/idVendor
	echo 02E2 > /sys/class/android_usb/android$num/idProduct
	echo 2 > /sys/class/android_usb/android$num/bDeviceClass
	echo 0 > /sys/class/android_usb/android$num/bDeviceSubClass
	echo 0 > /sys/class/android_usb/android$num/bDeviceProtocol
	echo AMTelecom > /sys/class/android_usb/android$num/iManufacturer
	echo 0123456789ABCDEF > /sys/class/android_usb/android$num/iSerial

	echo JMR1140 > /sys/class/android_usb/android$num/iProduct
	
	echo diag > /sys/class/android_usb/android$num/f_diag/clients
	echo smd > /sys/class/android_usb/android$num/f_serial/transports
	echo rndis,diag,serial:ecm > /sys/class/android_usb/android$num/functions
	echo 1 > /sys/class/android_usb/android$num/remote_wakeup
	echo 1 > /sys/class/android_usb/android0/f_rndis/wceis
	sleep $delay
	echo 1 > /sys/class/android_usb/android$num/enable

}

run_mass_storage() {
	if [ $from_adb = "n" ]
	then
		pkill adbd
	fi
	echo 0 > /sys/class/android_usb/android$num/enable
	echo 1ECB > /sys/class/android_usb/android$num/idVendor
	echo 02E2 > /sys/class/android_usb/android$num/idProduct
	echo 2 > /sys/class/android_usb/android$num/bDeviceClass
	echo 0 > /sys/class/android_usb/android$num/bDeviceSubClass
	echo 0 > /sys/class/android_usb/android$num/bDeviceProtocol
	echo AMTelecom > /sys/class/android_usb/android$num/iManufacturer
	echo 0123456789ABCDEF > /sys/class/android_usb/android$num/iSerial

	echo JMR1140 > /sys/class/android_usb/android$num/iProduct
	
	echo diag > /sys/class/android_usb/android$num/f_diag/clients
	echo smd > /sys/class/android_usb/android$num/f_serial/transports
	echo rndis,diag,serial,mass_storage:ecm > /sys/class/android_usb/android$num/functions
	echo /dev/mmcblk0p1 > /sys/class/android_usb/f_mass_storage/lun/file
	echo 1 > /sys/class/android_usb/android$num/remote_wakeup
	echo 1 > /sys/class/android_usb/android0/f_rndis/wceis
	sleep $delay
	echo 1 > /sys/class/android_usb/android$num/enable

}

if [ $(cat /sys/devices/soc:smem_db/factory_mode) == "1" ]
then
	run_nomass &
else
	case `cat /sys/devices/soc:smem_db/debug_enable` in
		*1* )
			run_nomass &
			;;

		* )
			# Enable ADB in normal boot while preserving WiFi disk mode.
			if [ $(cat /sys/devices/soc:smem_db/wdisk_mode) == "1" ]
			then
				run_mass_storage &
			else
				run_nomass &
			fi

			;;

	esac
fi
